name: Rust Lint, Clippy & Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Lint & Clippy
        run: cargo fmt --check && cargo clippy --all-targets --verbose -- -D warnings

      - name: Tests
        run: cargo test
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
